### PR TITLE
Added Saskia Leggett to board

### PR DESCRIPTION
**Pull request by mitchellmarkoff**

### CODE REVIEW

**Comment by mitchellmarkoff** [comment]
Checks failed

**Comment by etrepum** [comment]
This looks fine, the failing check is unrelated

**Comment by mitchellmarkoff** [comment]
Ah thank you, I really appreciate that. Was just going to talk to Juliana
about that.

**Comment by etrepum** [comment]
A few things needed to be updated, just sorted that out in #181

**Pull request merged**
